# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "accepts-1.3.5" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.5.tgz";
        sha1 = "eb777df6011723a3b14e8a72c0805c8e86746bd2";
      };
    };
    "array-flatten-1.1.1" = {
      name = "array-flatten";
      packageName = "array-flatten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz";
        sha1 = "9a5f699051b1e7073328f2a008968b64ea2955d2";
      };
    };
    "bignumber.js-4.1.0" = {
      name = "bignumber.js";
      packageName = "bignumber.js";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bignumber.js/-/bignumber.js-4.1.0.tgz";
        sha512 = "eJzYkFYy9L4JzXsbymsFn3p54D+llV27oTQ+ziJG7WFRheJcNZilgVXMG0LoZtlQSKBsJdWtLFqOD0u+U0jZKA==";
      };
    };
    "body-parser-1.18.3" = {
      name = "body-parser";
      packageName = "body-parser";
      version = "1.18.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/body-parser/-/body-parser-1.18.3.tgz";
        sha1 = "5b292198ffdd553b3a0f20ded0592b956955c8b4";
      };
    };
    "buffer-equal-constant-time-1.0.1" = {
      name = "buffer-equal-constant-time";
      packageName = "buffer-equal-constant-time";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-equal-constant-time/-/buffer-equal-constant-time-1.0.1.tgz";
        sha1 = "f8e71132f7ffe6e01a5c9697a4c6f3e48d5cc819";
      };
    };
    "buffer-writer-2.0.0" = {
      name = "buffer-writer";
      packageName = "buffer-writer";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-writer/-/buffer-writer-2.0.0.tgz";
        sha512 = "a7ZpuTZU1TRtnwyCNW3I5dc0wWNC3VR9S++Ewyk2HHZdrO3CQJqSpd+95Us590V6AL7JqUAH2IwZ/398PmNFgw==";
      };
    };
    "bytes-3.0.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-3.0.0.tgz";
        sha1 = "d32815404d689699f85a4ea4fa8755dd13a96048";
      };
    };
    "content-disposition-0.5.2" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.2.tgz";
        sha1 = "0cf68bb9ddf5f2be7961c3a85178cb85dba78cb4";
      };
    };
    "content-type-1.0.4" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.4.tgz";
        sha512 = "hIP3EEPs8tB9AT1L+NUqtwOAps4mk2Zob89MWXMHjHWg9milF/j4osnnQLXBCBFBk/tvIG/tUc9mOUJiPBhPXA==";
      };
    };
    "cookie-0.3.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.3.1.tgz";
        sha1 = "e7e0a1f9ef43b4c8ba925c5c5a96e806d16873bb";
      };
    };
    "cookie-signature-1.0.6" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz";
        sha1 = "e303a882b342cc3ee8ca513a79999734dab3ae2c";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha1 = "9bcd52e14c097763e749b274c4346ed2e560b5a9";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha1 = "978857442c44749e4206613e37946205826abd80";
      };
    };
    "double-ended-queue-2.1.0-0" = {
      name = "double-ended-queue";
      packageName = "double-ended-queue";
      version = "2.1.0-0";
      src = fetchurl {
        url = "https://registry.npmjs.org/double-ended-queue/-/double-ended-queue-2.1.0-0.tgz";
        sha1 = "103d3527fd31528f40188130c841efdd78264e5c";
      };
    };
    "ecdsa-sig-formatter-1.0.10" = {
      name = "ecdsa-sig-formatter";
      packageName = "ecdsa-sig-formatter";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecdsa-sig-formatter/-/ecdsa-sig-formatter-1.0.10.tgz";
        sha1 = "1c595000f04a8897dfb85000892a0f4c33af86c3";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "encodeurl-1.0.2" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz";
        sha1 = "ad3ff4c86ec2d029322f5a02c3a9a606c95b3f59";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "etag-1.8.1" = {
      name = "etag";
      packageName = "etag";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz";
        sha1 = "41ae2eeb65efa62268aebfea83ac7d79299b0887";
      };
    };
    "faye-websocket-0.10.0" = {
      name = "faye-websocket";
      packageName = "faye-websocket";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/faye-websocket/-/faye-websocket-0.10.0.tgz";
        sha1 = "4e492f8d04dfb6f89003507f6edbf2d501e7c6f4";
      };
    };
    "fd-slicer-1.1.0" = {
      name = "fd-slicer";
      packageName = "fd-slicer";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fd-slicer/-/fd-slicer-1.1.0.tgz";
        sha1 = "25c7c89cb1f9077f8891bbe61d8f390eae256f1e";
      };
    };
    "finalhandler-1.1.1" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-1.1.1.tgz";
        sha512 = "Y1GUDo39ez4aHAw7MysnUD5JzYX+WaIj8I57kO3aEPT1fFRL4sr7mjei97FgnwhAyyzRYmQZaTHb2+9uZ1dPtg==";
      };
    };
    "forwarded-0.1.2" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.1.2.tgz";
        sha1 = "98c23dab1175657b8c0573e8ceccd91b0ff18c84";
      };
    };
    "fresh-0.5.2" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.5.2.tgz";
        sha1 = "3d8cadd90d976569fa835ab1f8e4b23a105605a7";
      };
    };
    "http-errors-1.6.3" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.6.3.tgz";
        sha1 = "8b55680bb4be283a0b5bf4ea2e38580be1d9320d";
      };
    };
    "http-errors-1.7.1" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.7.1.tgz";
        sha512 = "jWEUgtZWGSMba9I1N3gc1HmvpBUaNC9vDdA46yScAdp+C5rdEuKWUBLWTQpW9FwSWSbYYs++b6SDCxf9UEJzfw==";
      };
    };
    "http-parser-js-0.5.0" = {
      name = "http-parser-js";
      packageName = "http-parser-js";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-parser-js/-/http-parser-js-0.5.0.tgz";
        sha512 = "cZdEF7r4gfRIq7ezX9J0T+kQmJNOub71dWbgAXVHDct80TKP4MCETtZQ31xyv38UwgzkWPYF/Xc0ge55dW9Z9w==";
      };
    };
    "iconv-lite-0.4.23" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.23.tgz";
        sha512 = "neyTUVFtahjf0mB3dZT77u+8O0QB89jFdnBkd5P1JgYPbPaia3gXXOVL2fq8VyU2gMMD7SaN7QukTB/pmXYvDA==";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "ipaddr.js-1.8.0" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.8.0.tgz";
        sha1 = "eaa33d6ddd7ace8f7f6fe0c9ca0440e706738b1e";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "json5-1.0.1" = {
      name = "json5";
      packageName = "json5";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-1.0.1.tgz";
        sha512 = "aKS4WQjPenRxiQsC93MNfjx+nbF4PAdYzmd/1JIj8HYzqfbu86beTuNgXDzPknWk0n0uARlyewZo4s++ES36Ow==";
      };
    };
    "jwa-1.2.0" = {
      name = "jwa";
      packageName = "jwa";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jwa/-/jwa-1.2.0.tgz";
        sha512 = "Grku9ZST5NNQ3hqNUodSkDfEBqAmGA1R8yiyPHOnLzEKI0GaCQC/XhFmsheXYuXzFQJdILbh+lYBiliqG5R/Vg==";
      };
    };
    "jws-3.2.1" = {
      name = "jws";
      packageName = "jws";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jws/-/jws-3.2.1.tgz";
        sha512 = "bGA2omSrFUkd72dhh05bIAN832znP4wOU3lfuXtRBuGTbsmNmDXMQg28f0Vsxaxgk4myF5YkKQpz6qeRpMgX9g==";
      };
    };
    "lodash.includes-4.3.0" = {
      name = "lodash.includes";
      packageName = "lodash.includes";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.includes/-/lodash.includes-4.3.0.tgz";
        sha1 = "60bb98a87cb923c68ca1e51325483314849f553f";
      };
    };
    "lodash.isboolean-3.0.3" = {
      name = "lodash.isboolean";
      packageName = "lodash.isboolean";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isboolean/-/lodash.isboolean-3.0.3.tgz";
        sha1 = "6c2e171db2a257cd96802fd43b01b20d5f5870f6";
      };
    };
    "lodash.isinteger-4.0.4" = {
      name = "lodash.isinteger";
      packageName = "lodash.isinteger";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isinteger/-/lodash.isinteger-4.0.4.tgz";
        sha1 = "619c0af3d03f8b04c31f5882840b77b11cd68343";
      };
    };
    "lodash.isnumber-3.0.3" = {
      name = "lodash.isnumber";
      packageName = "lodash.isnumber";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isnumber/-/lodash.isnumber-3.0.3.tgz";
        sha1 = "3ce76810c5928d03352301ac287317f11c0b1ffc";
      };
    };
    "lodash.isplainobject-4.0.6" = {
      name = "lodash.isplainobject";
      packageName = "lodash.isplainobject";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-4.0.6.tgz";
        sha1 = "7c526a52d89b45c45cc690b88163be0497f550cb";
      };
    };
    "lodash.isstring-4.0.1" = {
      name = "lodash.isstring";
      packageName = "lodash.isstring";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isstring/-/lodash.isstring-4.0.1.tgz";
        sha1 = "d527dfb5456eca7cc9bb95d5daeaf88ba54a5451";
      };
    };
    "lodash.once-4.1.1" = {
      name = "lodash.once";
      packageName = "lodash.once";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.once/-/lodash.once-4.1.1.tgz";
        sha1 = "0dd3971213c7c56df880977d504c88fb471a97ac";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
    "merge-descriptors-1.0.1" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz";
        sha1 = "b00aaa556dd8b44568150ec9d1b953f3f90cbb61";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha1 = "5529a4d67654134edcc5266656835b0f851afcee";
      };
    };
    "mime-1.4.1" = {
      name = "mime";
      packageName = "mime";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.4.1.tgz";
        sha512 = "KI1+qOZu5DcW6wayYHSzR/tXKCDC5Om4s1z2QJjDULzLcmf3DvzS7oluY4HCTrc+9FiKmWUgeNLg7W3uIQvxtQ==";
      };
    };
    "mime-db-1.38.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.38.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.38.0.tgz";
        sha512 = "bqVioMFFzc2awcdJZIzR3HjZFX20QhilVS7hytkKrv7xFAn8bM1gzc/FOX2awLISvWe0PV8ptFKcon+wZ5qYkg==";
      };
    };
    "mime-types-2.1.22" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.22.tgz";
        sha512 = "aGl6TZGnhm/li6F7yx82bJiBZwgiEa4Hf6CNr8YO+r5UHr53tSTYZb102zyU50DOWWKeOv0uQLRL0/9EiKWCog==";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "moment-2.24.0" = {
      name = "moment";
      packageName = "moment";
      version = "2.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.24.0.tgz";
        sha512 = "bV7f+6l2QigeBBZSM/6yTNq4P2fNpSWj/0e7jQcy87A8e7o2nAfP/34/2ky5Vw4B9S446EtIhodAzkFCcR4dQg==";
      };
    };
    "moment-timezone-0.5.23" = {
      name = "moment-timezone";
      packageName = "moment-timezone";
      version = "0.5.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment-timezone/-/moment-timezone-0.5.23.tgz";
        sha512 = "WHFH85DkCfiNMDX5D3X7hpNH3/PUhjTGcD0U1SgfBGZxJ3qUmJh5FdvaFjcClxOvB3rzdfj4oRffbI38jEnC1w==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "ms-2.1.1" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.1.tgz";
        sha512 = "tgp+dl5cGk28utYktBsrFqA7HKgrhgPsg6Z/EfhWI4gl1Hwq8B/GmY/0oXZ6nF8hDVesS/FpnYaD/kOWhYQvyg==";
      };
    };
    "negotiator-0.6.1" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz";
        sha1 = "2b327184e8992101177b28563fb5e7102acd0ca9";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "packet-reader-0.3.1" = {
      name = "packet-reader";
      packageName = "packet-reader";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/packet-reader/-/packet-reader-0.3.1.tgz";
        sha1 = "cd62e60af8d7fea8a705ec4ff990871c46871f27";
      };
    };
    "parseurl-1.3.2" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.2.tgz";
        sha1 = "fc289d4ed8993119460c156253262cdc8de65bf3";
      };
    };
    "path-to-regexp-0.1.7" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz";
        sha1 = "df604178005f522f15eb4490e7247a1bfaa67f8c";
      };
    };
    "pend-1.2.0" = {
      name = "pend";
      packageName = "pend";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pend/-/pend-1.2.0.tgz";
        sha1 = "7a57eb550a6783f9115331fcf4663d5c8e007a50";
      };
    };
    "pg-connection-string-0.1.3" = {
      name = "pg-connection-string";
      packageName = "pg-connection-string";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-connection-string/-/pg-connection-string-0.1.3.tgz";
        sha1 = "da1847b20940e42ee1492beaf65d49d91b245df7";
      };
    };
    "pg-int8-1.0.1" = {
      name = "pg-int8";
      packageName = "pg-int8";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-int8/-/pg-int8-1.0.1.tgz";
        sha512 = "WCtabS6t3c8SkpDBUlb1kjOs7l66xsGdKpIPZsg4wR+B3+u9UAum2odSsF9tnvxg80h4ZxLWMy4pRjOsFIqQpw==";
      };
    };
    "pg-pool-2.0.6" = {
      name = "pg-pool";
      packageName = "pg-pool";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-pool/-/pg-pool-2.0.6.tgz";
        sha512 = "hod2zYQxM8Gt482q+qONGTYcg/qVcV32VHVPtktbBJs0us3Dj7xibISw0BAAXVMCzt8A/jhfJvpZaxUlqtqs0g==";
      };
    };
    "pg-types-2.0.0" = {
      name = "pg-types";
      packageName = "pg-types";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-types/-/pg-types-2.0.0.tgz";
        sha512 = "THUD7gQll5tys+5eQ8Rvs7DjHiIC3bLqixk3gMN9Hu8UrCBAOjf35FoI39rTGGc3lM2HU/R+Knpxvd11mCwOMA==";
      };
    };
    "pgpass-1.0.2" = {
      name = "pgpass";
      packageName = "pgpass";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pgpass/-/pgpass-1.0.2.tgz";
        sha1 = "2a7bb41b6065b67907e91da1b07c1847c877b306";
      };
    };
    "postgres-array-2.0.0" = {
      name = "postgres-array";
      packageName = "postgres-array";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-array/-/postgres-array-2.0.0.tgz";
        sha512 = "VpZrUqU5A69eQyW2c5CA1jtLecCsN2U/bD6VilrFDWq5+5UIEVO7nazS3TEcHf1zuPYO/sqGvUvW62g86RXZuA==";
      };
    };
    "postgres-bytea-1.0.0" = {
      name = "postgres-bytea";
      packageName = "postgres-bytea";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-bytea/-/postgres-bytea-1.0.0.tgz";
        sha1 = "027b533c0aa890e26d172d47cf9ccecc521acd35";
      };
    };
    "postgres-date-1.0.3" = {
      name = "postgres-date";
      packageName = "postgres-date";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-date/-/postgres-date-1.0.3.tgz";
        sha1 = "e2d89702efdb258ff9d9cee0fe91bd06975257a8";
      };
    };
    "postgres-interval-1.1.2" = {
      name = "postgres-interval";
      packageName = "postgres-interval";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-interval/-/postgres-interval-1.1.2.tgz";
        sha512 = "fC3xNHeTskCxL1dC8KOtxXt7YeFmlbTYtn7ul8MkVERuTmf7pI4DrkAxcw3kh1fQ9uz4wQmd03a1mRiXUZChfQ==";
      };
    };
    "process-nextick-args-2.0.0" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.0.tgz";
        sha512 = "MtEC1TqN0EU5nephaJ4rAtThHtC86dNN9qCuEhtshvpVBkAW5ZO7BASN9REnF9eoXGcRub+pFuKEpOHE+HbEMw==";
      };
    };
    "proxy-addr-2.0.4" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-2.0.4.tgz";
        sha512 = "5erio2h9jp5CHGwcybmxmVqHmnCBZeewlfJ0pex+UW7Qny7OOZXTtH56TGNyBizkgiOwhJtMKrVzDTeKcySZwA==";
      };
    };
    "qs-6.5.2" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.2.tgz";
        sha512 = "N5ZAX4/LxJmF+7wN74pUD6qAh9/wnvdQcjq9TZjevvXzSUo7bfmw91saqMjzGS2xq91/odN2dW/WOl7qQHNDGA==";
      };
    };
    "random-bytes-1.0.0" = {
      name = "random-bytes";
      packageName = "random-bytes";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/random-bytes/-/random-bytes-1.0.0.tgz";
        sha1 = "4f68a1dc0ae58bd3fb95848c30324db75d64360b";
      };
    };
    "range-parser-1.2.0" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.0.tgz";
        sha1 = "f49be6b487894ddc40dcc94a322f611092e00d5e";
      };
    };
    "raw-body-2.3.3" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-2.3.3.tgz";
        sha512 = "9esiElv1BrZoI3rCDuOuKCBRbuApGGaDPQfjSflGxdy4oyzqghxu6klEkkVIvBje+FF0BX9coEv8KqW6X/7njw==";
      };
    };
    "readable-stream-2.3.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.6.tgz";
        sha512 = "tQtKA9WIAhBF3+VLAseyMqZeBjW0AHJoxOtYqSUZNJxauErmLbVm2FW1y+J/YA9dUrAC39ITejlZWhVIwawkKw==";
      };
    };
    "redis-2.6.0-0" = {
      name = "redis";
      packageName = "redis";
      version = "2.6.0-0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis/-/redis-2.6.0-0.tgz";
        sha1 = "73f674dd3e54a3a76703d1ed2606b4e600be076d";
      };
    };
    "redis-commands-1.4.0" = {
      name = "redis-commands";
      packageName = "redis-commands";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-commands/-/redis-commands-1.4.0.tgz";
        sha512 = "cu8EF+MtkwI4DLIT0x9P8qNTLFhQD4jLfxLR0cCNkeGzs87FN6879JOJwNQR/1zD7aSYNbU0hgsV9zGY71Itvw==";
      };
    };
    "redis-parser-1.3.0" = {
      name = "redis-parser";
      packageName = "redis-parser";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-parser/-/redis-parser-1.3.0.tgz";
        sha1 = "806ebe7bbfb7d34e4d7c1e9ef282efcfad04126a";
      };
    };
    "redis-parser-2.6.0" = {
      name = "redis-parser";
      packageName = "redis-parser";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-parser/-/redis-parser-2.6.0.tgz";
        sha1 = "52ed09dacac108f1a631c07e9b69941e7a19504b";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "semver-4.3.2" = {
      name = "semver";
      packageName = "semver";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-4.3.2.tgz";
        sha1 = "c7a07158a80bedd052355b770d82d6640f803be7";
      };
    };
    "send-0.16.2" = {
      name = "send";
      packageName = "send";
      version = "0.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.16.2.tgz";
        sha512 = "E64YFPUssFHEFBvpbbjr44NCLtI1AohxQ8ZSiJjQLskAdKuriYEP6VyGEsRDH8ScozGpkaX1BGvhanqCwkcEZw==";
      };
    };
    "serve-static-1.13.2" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.13.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.13.2.tgz";
        sha512 = "p/tdJrO4U387R9oMjb1oj7qSMaMfmOyd4j9hOFoxZe2baQszgHcSWjuya/CiT5kgZZKRudHNOA0pYXOl8rQ5nw==";
      };
    };
    "setprototypeof-1.1.0" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.1.0.tgz";
        sha512 = "BvE/TwpZX4FXExxOxZyRGQQv651MSwmWKZGqvmPcRIjDqWub67kTKuIMx43cZZrS/cBBzwBcNDWoFxt2XEFIpQ==";
      };
    };
    "split-1.0.1" = {
      name = "split";
      packageName = "split";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/split/-/split-1.0.1.tgz";
        sha512 = "mTyOoPbrivtXnwnIxZRFYRrPNtEFKlpB2fvjSnCQUiAA6qAZzqwna5envK4uk6OIeP17CsdF3rSBGYVBsU0Tkg==";
      };
    };
    "sqlstring-2.3.1" = {
      name = "sqlstring";
      packageName = "sqlstring";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sqlstring/-/sqlstring-2.3.1.tgz";
        sha1 = "475393ff9e91479aea62dcaf0ca3d14983a7fb40";
      };
    };
    "statuses-1.4.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.4.0.tgz";
        sha512 = "zhSCtt8v2NDrRlPQpCNtw/heZLtfUDqxBM1udqikb/Hbk52LK4nQSwr10u77iopCW5LsyHpuXS0GnEc48mLeew==";
      };
    };
    "statuses-1.5.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz";
        sha1 = "161c7dac177659fd9811f43771fa99381478628c";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "toidentifier-1.0.0" = {
      name = "toidentifier";
      packageName = "toidentifier";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.0.tgz";
        sha512 = "yaOH/Pk/VEhBWWTlhI+qXxDFXlejDGcQipMlyxda9nthulaxLZUNcUqFxokp0vcYnvteJln5FNQDRrxj3YcbVw==";
      };
    };
    "type-is-1.6.16" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.16.tgz";
        sha512 = "HRkVv/5qY2G6I8iab9cI7v1bOIdhm94dVjQCPFElW9W+3GeDOSHmy2EBYe4VTApuzolPcmgFTN3ftVJRKR2J9Q==";
      };
    };
    "uid-safe-2.1.5" = {
      name = "uid-safe";
      packageName = "uid-safe";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/uid-safe/-/uid-safe-2.1.5.tgz";
        sha512 = "KPHm4VL5dDXKz01UuEd88Df+KzynaohSL9fBh096KWAxSKZQDI2uBrVqtvRM4rwrIrRRKsdLNML/lnaaVSRioA==";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "utils-merge-1.0.1" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.1.tgz";
        sha1 = "9f95710f50a267947b2ccc124741c1028427e713";
      };
    };
    "uuid-3.3.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.3.2.tgz";
        sha512 = "yXJmeNaw3DnnKAOKJE51sL/ZaYfWJRl1pK9dr19YFCu0ObS231AB1/LbqTKRAQ5kw8A90rA6fr4riOUpTZvQZA==";
      };
    };
    "vary-1.1.2" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
        sha1 = "2299f02c6ded30d4a5961b0b9f74524a18f634fc";
      };
    };
    "websocket-driver-0.7.0" = {
      name = "websocket-driver";
      packageName = "websocket-driver";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.7.0.tgz";
        sha1 = "0caf9d2d755d93aee049d4bdd0d3fe2cca2a24eb";
      };
    };
    "websocket-extensions-0.1.3" = {
      name = "websocket-extensions";
      packageName = "websocket-extensions";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/websocket-extensions/-/websocket-extensions-0.1.3.tgz";
        sha512 = "nqHUnMXmBzT0w570r2JpJxfiSD1IzoI+HGVdd3aZ0yNi3ngvQ4jv1dtHt5VGxfI2yj5yqImPhOK4vmIh2xMbGg==";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
  };
in
{
  "base64-stream-^1.0.0" = nodeEnv.buildNodePackage {
    name = "base64-stream";
    packageName = "base64-stream";
    version = "1.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/base64-stream/-/base64-stream-1.0.0.tgz";
      sha512 = "BQQZftaO48FcE1Kof9CmXMFaAdqkcNorgc8CxesZv9nMbbTF1EFyQe89UOuh//QMmdtfUDXyO8rgUalemL5ODA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Contains new Node.js v0.10 style stream classes for encoding / decoding Base64 data";
      homepage = "https://github.com/mazira/base64-stream#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "body-parser-^1.18.3" = nodeEnv.buildNodePackage {
    name = "body-parser";
    packageName = "body-parser";
    version = "1.18.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/body-parser/-/body-parser-1.18.3.tgz";
      sha1 = "5b292198ffdd553b3a0f20ded0592b956955c8b4";
    };
    dependencies = [
      sources."bytes-3.0.0"
      sources."content-type-1.0.4"
      sources."debug-2.6.9"
      sources."depd-1.1.2"
      sources."ee-first-1.1.1"
      sources."http-errors-1.6.3"
      sources."iconv-lite-0.4.23"
      sources."inherits-2.0.3"
      sources."media-typer-0.3.0"
      sources."mime-db-1.38.0"
      sources."mime-types-2.1.22"
      sources."ms-2.0.0"
      sources."on-finished-2.3.0"
      sources."qs-6.5.2"
      sources."raw-body-2.3.3"
      sources."safer-buffer-2.1.2"
      sources."setprototypeof-1.1.0"
      sources."statuses-1.5.0"
      sources."type-is-1.6.16"
      sources."unpipe-1.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Node.js body parsing middleware";
      homepage = "https://github.com/expressjs/body-parser#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "co-^4.6.0" = nodeEnv.buildNodePackage {
    name = "co";
    packageName = "co";
    version = "4.6.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
      sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "generator async control flow goodness";
      homepage = "https://github.com/tj/co#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "config-^2.0.1" = nodeEnv.buildNodePackage {
    name = "config";
    packageName = "config";
    version = "2.0.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/config/-/config-2.0.2.tgz";
      sha512 = "duIbkKb0gls0bOtGwd1vaD4236MwepQlZcrMheOGrn3/9Px7oYFh8G4LB3ylGOlPr5wGoJRm8Grb2RihJZxuHQ==";
    };
    dependencies = [
      sources."json5-1.0.1"
      sources."minimist-1.2.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Configuration control for production node deployments";
      homepage = http://lorenwest.github.com/node-config;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "cron-^1.5.0" = nodeEnv.buildNodePackage {
    name = "cron";
    packageName = "cron";
    version = "1.6.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/cron/-/cron-1.6.0.tgz";
      sha512 = "8OkXbeK3qF42ndzkIkCo3zfCDg2TxGjQiCQqVE+ZFFHa4vAcw0PdBc5i/6aJ9FppLncyKZmDuZdJ9/uuXEYZaw==";
    };
    dependencies = [
      sources."moment-2.24.0"
      sources."moment-timezone-0.5.23"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Cron jobs for your node";
      homepage = "https://github.com/kelektiv/node-cron#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "deep-equal-^1.0.1" = nodeEnv.buildNodePackage {
    name = "deep-equal";
    packageName = "deep-equal";
    version = "1.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/deep-equal/-/deep-equal-1.0.1.tgz";
      sha1 = "f5d260292b660e084eff4cdbc9f08ad3247448b5";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "node's assert.deepEqual algorithm";
      homepage = "https://github.com/substack/node-deep-equal#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "express-^4.16.4" = nodeEnv.buildNodePackage {
    name = "express";
    packageName = "express";
    version = "4.16.4";
    src = fetchurl {
      url = "https://registry.npmjs.org/express/-/express-4.16.4.tgz";
      sha512 = "j12Uuyb4FMrd/qQAm6uCHAkPtO8FDTRJZBDd5D2KOL2eLaz1yUNdUB/NOIyq0iU4q4cFarsUCrnFDPBcnksuOg==";
    };
    dependencies = [
      sources."accepts-1.3.5"
      sources."array-flatten-1.1.1"
      sources."body-parser-1.18.3"
      sources."bytes-3.0.0"
      sources."content-disposition-0.5.2"
      sources."content-type-1.0.4"
      sources."cookie-0.3.1"
      sources."cookie-signature-1.0.6"
      sources."debug-2.6.9"
      sources."depd-1.1.2"
      sources."destroy-1.0.4"
      sources."ee-first-1.1.1"
      sources."encodeurl-1.0.2"
      sources."escape-html-1.0.3"
      sources."etag-1.8.1"
      sources."finalhandler-1.1.1"
      sources."forwarded-0.1.2"
      sources."fresh-0.5.2"
      sources."http-errors-1.6.3"
      sources."iconv-lite-0.4.23"
      sources."inherits-2.0.3"
      sources."ipaddr.js-1.8.0"
      sources."media-typer-0.3.0"
      sources."merge-descriptors-1.0.1"
      sources."methods-1.1.2"
      sources."mime-1.4.1"
      sources."mime-db-1.38.0"
      sources."mime-types-2.1.22"
      sources."ms-2.0.0"
      sources."negotiator-0.6.1"
      sources."on-finished-2.3.0"
      sources."parseurl-1.3.2"
      sources."path-to-regexp-0.1.7"
      sources."proxy-addr-2.0.4"
      sources."qs-6.5.2"
      sources."range-parser-1.2.0"
      sources."raw-body-2.3.3"
      sources."safe-buffer-5.1.2"
      sources."safer-buffer-2.1.2"
      sources."send-0.16.2"
      sources."serve-static-1.13.2"
      sources."setprototypeof-1.1.0"
      sources."statuses-1.4.0"
      sources."type-is-1.6.16"
      sources."unpipe-1.0.0"
      sources."utils-merge-1.0.1"
      sources."vary-1.1.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fast, unopinionated, minimalist web framework";
      homepage = http://expressjs.com/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "fakeredis-^2.0.0" = nodeEnv.buildNodePackage {
    name = "fakeredis";
    packageName = "fakeredis";
    version = "2.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/fakeredis/-/fakeredis-2.0.0.tgz";
      sha1 = "752fb832819ace31be88668cf1358d6f1438afc0";
    };
    dependencies = [
      sources."double-ended-queue-2.1.0-0"
      sources."redis-2.6.0-0"
      sources."redis-commands-1.4.0"
      sources."redis-parser-1.3.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fake redis for testing, works as a drop-in replacement for node_redis";
      homepage = "https://github.com/hdachev/fakeredis#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "jsonwebtoken-^8.3.0" = nodeEnv.buildNodePackage {
    name = "jsonwebtoken";
    packageName = "jsonwebtoken";
    version = "8.4.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/jsonwebtoken/-/jsonwebtoken-8.4.0.tgz";
      sha512 = "coyXjRTCy0pw5WYBpMvWOMN+Kjaik2MwTUIq9cna/W7NpO9E+iYbumZONAz3hcr+tXFJECoQVrtmIoC3Oz0gvg==";
    };
    dependencies = [
      sources."buffer-equal-constant-time-1.0.1"
      sources."ecdsa-sig-formatter-1.0.10"
      sources."jwa-1.2.0"
      sources."jws-3.2.1"
      sources."lodash.includes-4.3.0"
      sources."lodash.isboolean-3.0.3"
      sources."lodash.isinteger-4.0.4"
      sources."lodash.isnumber-3.0.3"
      sources."lodash.isplainobject-4.0.6"
      sources."lodash.isstring-4.0.1"
      sources."lodash.once-4.1.1"
      sources."ms-2.1.1"
      sources."safe-buffer-5.1.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "JSON Web Token implementation (symmetric and asymmetric)";
      homepage = "https://github.com/auth0/node-jsonwebtoken#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "jwa-^1.1.6" = nodeEnv.buildNodePackage {
    name = "jwa";
    packageName = "jwa";
    version = "1.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/jwa/-/jwa-1.2.0.tgz";
      sha512 = "Grku9ZST5NNQ3hqNUodSkDfEBqAmGA1R8yiyPHOnLzEKI0GaCQC/XhFmsheXYuXzFQJdILbh+lYBiliqG5R/Vg==";
    };
    dependencies = [
      sources."buffer-equal-constant-time-1.0.1"
      sources."ecdsa-sig-formatter-1.0.10"
      sources."safe-buffer-5.1.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "JWA implementation (supports all JWS algorithms)";
      homepage = "https://github.com/brianloveswords/node-jwa#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "mime-^2.3.1" = nodeEnv.buildNodePackage {
    name = "mime";
    packageName = "mime";
    version = "2.4.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/mime/-/mime-2.4.0.tgz";
      sha512 = "ikBcWwyqXQSHKtciCcctu9YfPbFYZ4+gbHEmE0Q8jzcTYQg5dHCr3g2wwAZjPoJfQVXZq6KXAjpXOTf5/cjT7w==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "A comprehensive library for mime-type mapping";
      homepage = "https://github.com/broofa/node-mime#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "ms-^2.1.1" = nodeEnv.buildNodePackage {
    name = "ms";
    packageName = "ms";
    version = "2.1.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/ms/-/ms-2.1.1.tgz";
      sha512 = "tgp+dl5cGk28utYktBsrFqA7HKgrhgPsg6Z/EfhWI4gl1Hwq8B/GmY/0oXZ6nF8hDVesS/FpnYaD/kOWhYQvyg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Tiny millisecond conversion utility";
      homepage = "https://github.com/zeit/ms#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "multiparty-^4.2.1" = nodeEnv.buildNodePackage {
    name = "multiparty";
    packageName = "multiparty";
    version = "4.2.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/multiparty/-/multiparty-4.2.1.tgz";
      sha512 = "AvESCnNoQlZiOfP9R4mxN8M9csy2L16EIbWIkt3l4FuGti9kXBS8QVzlfyg4HEnarJhrzZilgNFlZtqmoiAIIA==";
    };
    dependencies = [
      sources."depd-1.1.2"
      sources."fd-slicer-1.1.0"
      sources."http-errors-1.7.1"
      sources."inherits-2.0.3"
      sources."pend-1.2.0"
      sources."random-bytes-1.0.0"
      sources."safe-buffer-5.1.2"
      sources."setprototypeof-1.1.0"
      sources."statuses-1.5.0"
      sources."toidentifier-1.0.0"
      sources."uid-safe-2.1.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "multipart/form-data parser which supports streaming";
      homepage = "https://github.com/pillarjs/multiparty#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "mysql-^2.16.0" = nodeEnv.buildNodePackage {
    name = "mysql";
    packageName = "mysql";
    version = "2.16.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/mysql/-/mysql-2.16.0.tgz";
      sha512 = "dPbN2LHonQp7D5ja5DJXNbCLe/HRdu+f3v61aguzNRQIrmZLOeRoymBYyeThrR6ug+FqzDL95Gc9maqZUJS+Gw==";
    };
    dependencies = [
      sources."bignumber.js-4.1.0"
      sources."core-util-is-1.0.2"
      sources."inherits-2.0.3"
      sources."isarray-1.0.0"
      sources."process-nextick-args-2.0.0"
      sources."readable-stream-2.3.6"
      sources."safe-buffer-5.1.2"
      sources."sqlstring-2.3.1"
      sources."string_decoder-1.1.1"
      sources."util-deprecate-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A node.js driver for mysql. It is written in JavaScript, does not require compiling, and is 100% MIT licensed.";
      homepage = "https://github.com/mysqljs/mysql#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "pg-^7.6.0" = nodeEnv.buildNodePackage {
    name = "pg";
    packageName = "pg";
    version = "7.8.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/pg/-/pg-7.8.0.tgz";
      sha512 = "yS3C9YD+ft0H7G47uU0eKajgTieggCXdA+Fxhm5G+wionY6kPBa8BEVDwPLMxQvkRkv3/LXiFEqjZm9gfxdW+g==";
    };
    dependencies = [
      sources."buffer-writer-2.0.0"
      sources."packet-reader-0.3.1"
      sources."pg-connection-string-0.1.3"
      sources."pg-int8-1.0.1"
      sources."pg-pool-2.0.6"
      sources."pg-types-2.0.0"
      sources."pgpass-1.0.2"
      sources."postgres-array-2.0.0"
      sources."postgres-bytea-1.0.0"
      sources."postgres-date-1.0.3"
      sources."postgres-interval-1.1.2"
      sources."semver-4.3.2"
      sources."split-1.0.1"
      sources."through-2.3.8"
      sources."xtend-4.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "PostgreSQL client - pure javascript & libpq with the same API";
      homepage = http://github.com/brianc/node-postgres;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "pg-escape-^0.2.0" = nodeEnv.buildNodePackage {
    name = "pg-escape";
    packageName = "pg-escape";
    version = "0.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/pg-escape/-/pg-escape-0.2.0.tgz";
      sha1 = "65594c1691659b4ab6e0cbbf9d50744be474998e";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "escape postgres queries which do not support stored procedures";
      homepage = "https://github.com/segmentio/pg-escape#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "redis-^2.8.0" = nodeEnv.buildNodePackage {
    name = "redis";
    packageName = "redis";
    version = "2.8.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/redis/-/redis-2.8.0.tgz";
      sha512 = "M1OkonEQwtRmZv4tEWF2VgpG0JWJ8Fv1PhlgT5+B+uNq2cA3Rt1Yt/ryoR+vQNOQcIEgdCdfH0jr3bDpihAw1A==";
    };
    dependencies = [
      sources."double-ended-queue-2.1.0-0"
      sources."redis-commands-1.4.0"
      sources."redis-parser-2.6.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Redis client library";
      homepage = https://github.com/NodeRedis/node_redis;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "sockjs-^0.3.19" = nodeEnv.buildNodePackage {
    name = "sockjs";
    packageName = "sockjs";
    version = "0.3.19";
    src = fetchurl {
      url = "https://registry.npmjs.org/sockjs/-/sockjs-0.3.19.tgz";
      sha512 = "V48klKZl8T6MzatbLlzzRNhMepEys9Y4oGFpypBFFn1gLI/QQ9HtLLyWJNbPlwGLelOVOEijUbTTJeLLI59jLw==";
    };
    dependencies = [
      sources."faye-websocket-0.10.0"
      sources."http-parser-js-0.5.0"
      sources."uuid-3.3.2"
      sources."websocket-driver-0.7.0"
      sources."websocket-extensions-0.1.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "SockJS-node is a server counterpart of SockJS-client a JavaScript library that provides a WebSocket-like object in the browser. SockJS gives you a coherent, cross-browser, Javascript API which creates a low latency, full duplex, cross-domain communication";
      homepage = https://github.com/sockjs/sockjs-node;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "underscore-^1.9.1" = nodeEnv.buildNodePackage {
    name = "underscore";
    packageName = "underscore";
    version = "1.9.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/underscore/-/underscore-1.9.1.tgz";
      sha512 = "5/4etnCkd9c8gwgowi5/om/mYO5ajCaOgdzj/oW+0eQV9WxKBDZw5+ycmKmeaTXjInS/W0BzpGLo2xR2aBwZdg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "JavaScript's functional programming helper library.";
      homepage = http://underscorejs.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
}