# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "abbrev-1.1.1" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
        sha512 = "nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q==";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "argparse-0.1.16" = {
      name = "argparse";
      packageName = "argparse";
      version = "0.1.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-0.1.16.tgz";
        sha1 = "cfd01e0fbba3d6caed049fbd758d40f65196f57c";
      };
    };
    "arr-diff-2.0.0" = {
      name = "arr-diff";
      packageName = "arr-diff";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-diff/-/arr-diff-2.0.0.tgz";
        sha1 = "8f3b827f955a8bd669697e4a4256ac3ceae356cf";
      };
    };
    "arr-flatten-1.1.0" = {
      name = "arr-flatten";
      packageName = "arr-flatten";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-flatten/-/arr-flatten-1.1.0.tgz";
        sha512 = "L3hKV5R/p5o81R7O02IGnwpDmkp6E982XhtbuwSe3O4qOtMMMtodicASA1Cny2U+aCXcNpml+m4dPsvsJ3jatg==";
      };
    };
    "array-unique-0.2.1" = {
      name = "array-unique";
      packageName = "array-unique";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-unique/-/array-unique-0.2.1.tgz";
        sha1 = "a1d97ccafcbc2625cc70fadceb36a50c58b01a53";
      };
    };
    "async-0.1.22" = {
      name = "async";
      packageName = "async";
      version = "0.1.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.1.22.tgz";
        sha1 = "0fc1aaa088a0e3ef0ebe2d8831bab0dcf8845061";
      };
    };
    "async-1.5.2" = {
      name = "async";
      packageName = "async";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.5.2.tgz";
        sha1 = "ec6a61ae56480c0c3cb241c95618e20892f9672a";
      };
    };
    "babel-runtime-6.26.0" = {
      name = "babel-runtime";
      packageName = "babel-runtime";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.26.0.tgz";
        sha1 = "965c7058668e82b55d7bfe04ff2337bc8b5647fe";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "bower-config-1.4.1" = {
      name = "bower-config";
      packageName = "bower-config";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bower-config/-/bower-config-1.4.1.tgz";
        sha1 = "85fd9df367c2b8dbbd0caa4c5f2bad40cd84c2cc";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "braces-1.8.5" = {
      name = "braces";
      packageName = "braces";
      version = "1.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-1.8.5.tgz";
        sha1 = "ba77962e12dff969d6b76711e914b737857bf6a7";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "check-dependencies-0.12.3" = {
      name = "check-dependencies";
      packageName = "check-dependencies";
      version = "0.12.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/check-dependencies/-/check-dependencies-0.12.3.tgz";
        sha1 = "6ba493d4221dbc3f695113353ae4638f772c5c75";
      };
    };
    "coffee-script-1.3.3" = {
      name = "coffee-script";
      packageName = "coffee-script";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/coffee-script/-/coffee-script-1.3.3.tgz";
        sha1 = "150d6b4cb522894369efed6a2101c20bc7f4a4f4";
      };
    };
    "colors-0.6.2" = {
      name = "colors";
      packageName = "colors";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-0.6.2.tgz";
        sha1 = "2423fe6678ac0c5dae8852e5d0e5be08c997abcc";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "core-js-2.6.5" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.6.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.6.5.tgz";
        sha512 = "klh/kDpwX8hryYL14M9w/xei6vrv6sE8gTHDG7/T/+SEovB/G4ejwcfE/CBzO6Edsu+OETZMZ3wcX/EjUkrl5A==";
      };
    };
    "dateformat-1.0.2-1.2.3" = {
      name = "dateformat";
      packageName = "dateformat";
      version = "1.0.2-1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dateformat/-/dateformat-1.0.2-1.2.3.tgz";
        sha1 = "b0220c02de98617433b72851cf47de3df2cdbee9";
      };
    };
    "detect-file-0.1.0" = {
      name = "detect-file";
      packageName = "detect-file";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-file/-/detect-file-0.1.0.tgz";
        sha1 = "4935dedfd9488648e006b0129566e9386711ea63";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esprima-1.0.4" = {
      name = "esprima";
      packageName = "esprima";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-1.0.4.tgz";
        sha1 = "9f557e08fc3b4d26ece9dd34f8fbf476b62585ad";
      };
    };
    "eventemitter2-0.4.14" = {
      name = "eventemitter2";
      packageName = "eventemitter2";
      version = "0.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter2/-/eventemitter2-0.4.14.tgz";
        sha1 = "8f61b75cde012b2e9eb284d4545583b5643b61ab";
      };
    };
    "exit-0.1.2" = {
      name = "exit";
      packageName = "exit";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/exit/-/exit-0.1.2.tgz";
        sha1 = "0632638f8d877cc82107d30a0fff1a17cba1cd0c";
      };
    };
    "expand-brackets-0.1.5" = {
      name = "expand-brackets";
      packageName = "expand-brackets";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-brackets/-/expand-brackets-0.1.5.tgz";
        sha1 = "df07284e342a807cd733ac5af72411e581d1177b";
      };
    };
    "expand-range-1.8.2" = {
      name = "expand-range";
      packageName = "expand-range";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-range/-/expand-range-1.8.2.tgz";
        sha1 = "a299effd335fe2721ebae8e257ec79644fc85337";
      };
    };
    "expand-tilde-1.2.2" = {
      name = "expand-tilde";
      packageName = "expand-tilde";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-tilde/-/expand-tilde-1.2.2.tgz";
        sha1 = "0b81eba897e5a3d31d1c3d102f8f01441e559449";
      };
    };
    "extglob-0.3.2" = {
      name = "extglob";
      packageName = "extglob";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extglob/-/extglob-0.3.2.tgz";
        sha1 = "2e18ff3d2f49ab2765cec9023f011daa8d8349a1";
      };
    };
    "file-sync-cmp-0.1.1" = {
      name = "file-sync-cmp";
      packageName = "file-sync-cmp";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-sync-cmp/-/file-sync-cmp-0.1.1.tgz";
        sha1 = "a5e7a8ffbfa493b43b923bbd4ca89a53b63b612b";
      };
    };
    "filename-regex-2.0.1" = {
      name = "filename-regex";
      packageName = "filename-regex";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/filename-regex/-/filename-regex-2.0.1.tgz";
        sha1 = "c1c4b9bee3e09725ddb106b75c1e301fe2f18b26";
      };
    };
    "fill-range-2.2.4" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-2.2.4.tgz";
        sha512 = "cnrcCbj01+j2gTG921VZPnHbjmdAf8oQV/iGeV2kZxGSyfYjjTyY79ErsK1WJWMpw6DaApEX72binqJE+/d+5Q==";
      };
    };
    "findup-sync-0.1.3" = {
      name = "findup-sync";
      packageName = "findup-sync";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/findup-sync/-/findup-sync-0.1.3.tgz";
        sha1 = "7f3e7a97b82392c653bf06589bd85190e93c3683";
      };
    };
    "findup-sync-0.4.3" = {
      name = "findup-sync";
      packageName = "findup-sync";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/findup-sync/-/findup-sync-0.4.3.tgz";
        sha1 = "40043929e7bc60adf0b7f4827c4c6e75a0deca12";
      };
    };
    "for-in-1.0.2" = {
      name = "for-in";
      packageName = "for-in";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-in/-/for-in-1.0.2.tgz";
        sha1 = "81068d295a8142ec0ac726c6e2200c30fb6d5e80";
      };
    };
    "for-own-0.1.5" = {
      name = "for-own";
      packageName = "for-own";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-own/-/for-own-0.1.5.tgz";
        sha1 = "5265c681a4f294dabbf17c9509b6763aa84510ce";
      };
    };
    "fs-exists-sync-0.1.0" = {
      name = "fs-exists-sync";
      packageName = "fs-exists-sync";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-exists-sync/-/fs-exists-sync-0.1.0.tgz";
        sha1 = "982d6893af918e72d08dec9e8673ff2b5a8d6add";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "getobject-0.1.0" = {
      name = "getobject";
      packageName = "getobject";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/getobject/-/getobject-0.1.0.tgz";
        sha1 = "047a449789fa160d018f5486ed91320b6ec7885c";
      };
    };
    "glob-3.1.21" = {
      name = "glob";
      packageName = "glob";
      version = "3.1.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-3.1.21.tgz";
        sha1 = "d29e0a055dea5138f4d07ed40e8982e83c2066cd";
      };
    };
    "glob-3.2.11" = {
      name = "glob";
      packageName = "glob";
      version = "3.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-3.2.11.tgz";
        sha1 = "4a973f635b9190f715d10987d5c00fd2815ebe3d";
      };
    };
    "glob-7.1.3" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.3.tgz";
        sha512 = "vcfuiIxogLV4DlGBHIUOwI0IbrJ8HWPc4MU7HzviGeNho/UJDfi6B5p3sHeWIQ0KGIU0Jpxi5ZHxemQfLkkAwQ==";
      };
    };
    "glob-base-0.3.0" = {
      name = "glob-base";
      packageName = "glob-base";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-base/-/glob-base-0.3.0.tgz";
        sha1 = "dbb164f6221b1c0b1ccf82aea328b497df0ea3c4";
      };
    };
    "glob-parent-2.0.0" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-2.0.0.tgz";
        sha1 = "81383d72db054fcccf5336daa902f182f6edbb28";
      };
    };
    "global-modules-0.2.3" = {
      name = "global-modules";
      packageName = "global-modules";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/global-modules/-/global-modules-0.2.3.tgz";
        sha1 = "ea5a3bed42c6d6ce995a4f8a1269b5dae223828d";
      };
    };
    "global-prefix-0.1.5" = {
      name = "global-prefix";
      packageName = "global-prefix";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/global-prefix/-/global-prefix-0.1.5.tgz";
        sha1 = "8d3bc6b8da3ca8112a160d8d496ff0462bfef78f";
      };
    };
    "graceful-fs-1.2.3" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-1.2.3.tgz";
        sha1 = "15a4806a57547cb2d2dbf27f42e89a8c3451b364";
      };
    };
    "graceful-fs-4.1.15" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.15.tgz";
        sha512 = "6uHUhOPEBgQ24HM+r6b/QwWfZq+yiFcipKFrOFiBEnWdy5sdzYoi+pJeQaPI5qOLRFqWmAXUPQNsielzdLoecA==";
      };
    };
    "grunt-legacy-log-0.1.3" = {
      name = "grunt-legacy-log";
      packageName = "grunt-legacy-log";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-log/-/grunt-legacy-log-0.1.3.tgz";
        sha1 = "ec29426e803021af59029f87d2f9cd7335a05531";
      };
    };
    "grunt-legacy-log-utils-0.1.1" = {
      name = "grunt-legacy-log-utils";
      packageName = "grunt-legacy-log-utils";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-log-utils/-/grunt-legacy-log-utils-0.1.1.tgz";
        sha1 = "c0706b9dd9064e116f36f23fe4e6b048672c0f7e";
      };
    };
    "grunt-legacy-util-0.2.0" = {
      name = "grunt-legacy-util";
      packageName = "grunt-legacy-util";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-util/-/grunt-legacy-util-0.2.0.tgz";
        sha1 = "93324884dbf7e37a9ff7c026dff451d94a9e554b";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "homedir-polyfill-1.0.1" = {
      name = "homedir-polyfill";
      packageName = "homedir-polyfill";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/homedir-polyfill/-/homedir-polyfill-1.0.1.tgz";
        sha1 = "4c2bbc8a758998feebf5ed68580f76d46768b4bc";
      };
    };
    "hooker-0.2.3" = {
      name = "hooker";
      packageName = "hooker";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hooker/-/hooker-0.2.3.tgz";
        sha1 = "b834f723cc4a242aa65963459df6d984c5d3d959";
      };
    };
    "iconv-lite-0.2.11" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.2.11.tgz";
        sha1 = "1ce60a3a57864a292d1321ff4609ca4bb965adc8";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-1.0.2" = {
      name = "inherits";
      packageName = "inherits";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-1.0.2.tgz";
        sha1 = "ca4309dadee6b54cc0b8d247e8d7c7a0975bdc9b";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "ini-1.3.5" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.5.tgz";
        sha512 = "RZY5huIKCMRWDUqZlEi72f/lmXKMvuszcMBduliQ3nnWbx9X/ZBQO7DijMEYS9EhHBb2qacRUMtC7svLwe0lcw==";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "NcdALwpXkTm5Zvvbk7owOUSvVvBKDgKP5/ewfXEznmQFfs4ZRmanOeKBTjRVjka3QFoN6XJ+9F3USqfHqTaU5w==";
      };
    };
    "is-dotfile-1.0.3" = {
      name = "is-dotfile";
      packageName = "is-dotfile";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-dotfile/-/is-dotfile-1.0.3.tgz";
        sha1 = "a6a2f32ffd2dfb04f5ca25ecd0f6b83cf798a1e1";
      };
    };
    "is-equal-shallow-0.1.3" = {
      name = "is-equal-shallow";
      packageName = "is-equal-shallow";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-equal-shallow/-/is-equal-shallow-0.1.3.tgz";
        sha1 = "2238098fc221de0bcfa5d9eac4c45d638aa1c534";
      };
    };
    "is-extendable-0.1.1" = {
      name = "is-extendable";
      packageName = "is-extendable";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extendable/-/is-extendable-0.1.1.tgz";
        sha1 = "62b110e289a471418e3ec36a617d472e301dfc89";
      };
    };
    "is-extglob-1.0.0" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-1.0.0.tgz";
        sha1 = "ac468177c4943405a092fc8f29760c6ffc6206c0";
      };
    };
    "is-glob-2.0.1" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-2.0.1.tgz";
        sha1 = "d096f926a3ded5600f3fdfd91198cb0888c2d863";
      };
    };
    "is-number-2.1.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-2.1.0.tgz";
        sha1 = "01fcbbb393463a548f2f466cce16dece49db908f";
      };
    };
    "is-number-4.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-4.0.0.tgz";
        sha512 = "rSklcAIlf1OmFdyAqbnWTLVelsQ58uvZ66S/ZyawjWqIviTWCjg2PzVGw8WUA+nNuPTqb4wgA+NszrJ+08LlgQ==";
      };
    };
    "is-posix-bracket-0.1.1" = {
      name = "is-posix-bracket";
      packageName = "is-posix-bracket";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-posix-bracket/-/is-posix-bracket-0.1.1.tgz";
        sha1 = "3334dc79774368e92f016e6fbc0a88f5cd6e6bc4";
      };
    };
    "is-primitive-2.0.0" = {
      name = "is-primitive";
      packageName = "is-primitive";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-primitive/-/is-primitive-2.0.0.tgz";
        sha1 = "207bab91638499c07b2adf240a41a87210034575";
      };
    };
    "is-windows-0.2.0" = {
      name = "is-windows";
      packageName = "is-windows";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-windows/-/is-windows-0.2.0.tgz";
        sha1 = "de1aa6d63ea29dd248737b69f1ff8b8002d2108c";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "isobject-2.1.0" = {
      name = "isobject";
      packageName = "isobject";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-2.1.0.tgz";
        sha1 = "f065561096a3f1da2ef46272f815c840d87e0c89";
      };
    };
    "js-yaml-2.0.5" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-2.0.5.tgz";
        sha1 = "a25ae6509999e97df278c6719da11bd0687743a8";
      };
    };
    "kind-of-3.2.2" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-3.2.2.tgz";
        sha1 = "31ea21a734bab9bbb0f32466d893aea51e4a3c64";
      };
    };
    "kind-of-6.0.2" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-6.0.2.tgz";
        sha512 = "s5kLOcnH0XqDO+FvuaLX8DDjZ18CGFk7VygH40QoKPUQhW4e2rvM0rwUq0t8IQDOwYSeLK01U90OjzBTme2QqA==";
      };
    };
    "lodash-0.9.2" = {
      name = "lodash";
      packageName = "lodash";
      version = "0.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-0.9.2.tgz";
        sha1 = "8f3499c5245d346d682e5b0d3b40767e09f1a92c";
      };
    };
    "lodash-2.4.2" = {
      name = "lodash";
      packageName = "lodash";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz";
        sha1 = "fadd834b9683073da179b3eae6d9c0d15053f73e";
      };
    };
    "lodash-4.17.11" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.11.tgz";
        sha512 = "cQKh8igo5QUhZ7lg38DYWAxMvjSAKG0A8wGSVimP07SIUEK2UO+arSRKbRZWtelMtN5V0Hkwh5ryOto/SshYIg==";
      };
    };
    "lodash.clonedeep-4.5.0" = {
      name = "lodash.clonedeep";
      packageName = "lodash.clonedeep";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.clonedeep/-/lodash.clonedeep-4.5.0.tgz";
        sha1 = "e23f3f9c4f8fbdde872529c1071857a086e5ccef";
      };
    };
    "lru-cache-2.7.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz";
        sha1 = "6d4524e8b955f95d4f5b58851ce21dd72fb4e952";
      };
    };
    "math-random-1.0.4" = {
      name = "math-random";
      packageName = "math-random";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/math-random/-/math-random-1.0.4.tgz";
        sha512 = "rUxjysqif/BZQH2yhd5Aaq7vXMSx9NdEsQcyA07uEzIvxgI7zIr33gGsh+RU0/XjmQpCW7RsVof1vlkvQVCK5A==";
      };
    };
    "micromatch-2.3.11" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "2.3.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-2.3.11.tgz";
        sha1 = "86677c97d1720b363431d04d0d15293bd38c1565";
      };
    };
    "minimatch-0.2.14" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "0.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-0.2.14.tgz";
        sha1 = "c74e780574f63c6f9a090e90efbe6ef53a6a756a";
      };
    };
    "minimatch-0.3.0" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-0.3.0.tgz";
        sha1 = "275d8edaac4f1bb3326472089e7949c8394699dd";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-0.0.10" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz";
        sha1 = "de3f98543dbf96082be48ad1a0c7cda836301dcf";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "mout-1.1.0" = {
      name = "mout";
      packageName = "mout";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mout/-/mout-1.1.0.tgz";
        sha512 = "XsP0vf4As6BfqglxZqbqQ8SR6KQot2AgxvR0gG+WtUkf90vUXchMOZQtPf/Hml1rEffJupqL/tIrU6EYhsUQjw==";
      };
    };
    "nopt-1.0.10" = {
      name = "nopt";
      packageName = "nopt";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-1.0.10.tgz";
        sha1 = "6ddd21bd2a31417b92727dd585f8a6f37608ebee";
      };
    };
    "normalize-path-2.1.1" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-2.1.1.tgz";
        sha1 = "1ab28b556e198363a8c1a6f7e6fa20137fe6aed9";
      };
    };
    "object.omit-2.0.1" = {
      name = "object.omit";
      packageName = "object.omit";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.omit/-/object.omit-2.0.1.tgz";
        sha1 = "1a9c744829f39dbb858c76ca3579ae2a54ebd1fa";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "optimist-0.6.1" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz";
        sha1 = "da3ea74686fa21a19a111c326e90eb15a0196686";
      };
    };
    "os-homedir-1.0.2" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.2.tgz";
        sha1 = "ffbc4988336e0e833de0c168c7ef152121aa7fb3";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha1 = "bbe67406c79aa85c5cfec766fe5734555dfa1274";
      };
    };
    "osenv-0.1.5" = {
      name = "osenv";
      packageName = "osenv";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/osenv/-/osenv-0.1.5.tgz";
        sha512 = "0CWcCECdMVc2Rw3U5w9ZjqX6ga6ubk1xDVKxtBQPK7wis/0F2r9T6k4ydGYhecl7YUBxBVxhL5oisPsNxAPe2g==";
      };
    };
    "parse-glob-3.0.4" = {
      name = "parse-glob";
      packageName = "parse-glob";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-glob/-/parse-glob-3.0.4.tgz";
        sha1 = "b2c376cfb11f35513badd173ef0bb6e3a388391c";
      };
    };
    "parse-passwd-1.0.0" = {
      name = "parse-passwd";
      packageName = "parse-passwd";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-passwd/-/parse-passwd-1.0.0.tgz";
        sha1 = "6d5b934a456993b23d37f40a382d6f1666a8e5c6";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "preserve-0.2.0" = {
      name = "preserve";
      packageName = "preserve";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/preserve/-/preserve-0.2.0.tgz";
        sha1 = "815ed1f6ebc65926f865b310c0713bcb3315ce4b";
      };
    };
    "randomatic-3.1.1" = {
      name = "randomatic";
      packageName = "randomatic";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/randomatic/-/randomatic-3.1.1.tgz";
        sha512 = "TuDE5KxZ0J461RVjrJZCJc+J+zCkTb1MbH9AQUq68sMhOMcy9jLcb3BrZKgp9q9Ncltdg4QVqWrH02W2EFFVYw==";
      };
    };
    "regenerator-runtime-0.11.1" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.11.1.tgz";
        sha512 = "MguG95oij0fC3QV3URf4V2SDYGJhJnJGqvIIgdECeODCT98wSWDAJ94SSuVpYQUoTcGUIL6L4yNB7j1DFFHSBg==";
      };
    };
    "regex-cache-0.4.4" = {
      name = "regex-cache";
      packageName = "regex-cache";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/regex-cache/-/regex-cache-0.4.4.tgz";
        sha512 = "nVIZwtCjkC9YgvWkpM55B5rBhBYRZhAaJbgcFYXXsHnbZ9UZI9nnVWYZpBlCqv9ho2eZryPnWrZGsOdPwVWXWQ==";
      };
    };
    "remove-trailing-separator-1.1.0" = {
      name = "remove-trailing-separator";
      packageName = "remove-trailing-separator";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remove-trailing-separator/-/remove-trailing-separator-1.1.0.tgz";
        sha1 = "c24bce2a283adad5bc3f58e0d48249b92379d8ef";
      };
    };
    "repeat-element-1.1.3" = {
      name = "repeat-element";
      packageName = "repeat-element";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-element/-/repeat-element-1.1.3.tgz";
        sha512 = "ahGq0ZnV5m5XtZLMb+vP76kcAM5nkLqk0lpqAuojSKGgQtn4eRi4ZZGm2olo2zKFH+sMsWaqOCW1dqAnOru72g==";
      };
    };
    "repeat-string-1.6.1" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz";
        sha1 = "8dcae470e1c88abc2d600fff4a776286da75e637";
      };
    };
    "resolve-dir-0.1.1" = {
      name = "resolve-dir";
      packageName = "resolve-dir";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-dir/-/resolve-dir-0.1.1.tgz";
        sha1 = "b219259a5602fac5c5c496ad894a6e8cc430261e";
      };
    };
    "rimraf-2.2.8" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz";
        sha1 = "e439be2aaee327321952730f99a8929e4fc50582";
      };
    };
    "rimraf-2.6.3" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.6.3.tgz";
        sha512 = "mwqeW5XsA2qAejG46gYdENaxXjx9onRNCfn7L0duuP4hCuTIi/QO7PDK07KJfp1d+izWPrzEJDcSqBa0OZQriA==";
      };
    };
    "semver-5.6.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.6.0.tgz";
        sha512 = "RS9R6R35NYgQn++fkDWaOmqGoj4Ek9gGs+DPxNUZKuwE183xjJroKvyo1IzVFeXvUrvmALy6FWD5xrdJT25gMg==";
      };
    };
    "sigmund-1.0.1" = {
      name = "sigmund";
      packageName = "sigmund";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz";
        sha1 = "3ff21f198cad2175f9f3b781853fd94d0d19b590";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "underscore-1.7.0" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz";
        sha1 = "6bbaf0877500d36be34ecaa584e0db9fef035209";
      };
    };
    "underscore.string-2.2.1" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-2.2.1.tgz";
        sha1 = "d7c0fa2af5d5a1a67f4253daee98132e733f0f19";
      };
    };
    "underscore.string-2.3.3" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-2.3.3.tgz";
        sha1 = "71c08bf6b428b1133f37e78fa3a21c82f7329b0d";
      };
    };
    "underscore.string-2.4.0" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-2.4.0.tgz";
        sha1 = "8cdd8fbac4e2d2ea1e7e2e8097c42f442280f85b";
      };
    };
    "untildify-2.1.0" = {
      name = "untildify";
      packageName = "untildify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/untildify/-/untildify-2.1.0.tgz";
        sha1 = "17eb2807987f76952e9c0485fc311d06a826a2e0";
      };
    };
    "which-1.0.9" = {
      name = "which";
      packageName = "which";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.0.9.tgz";
        sha1 = "460c1da0f810103d0321a9b633af9e575e64486f";
      };
    };
    "which-1.3.1" = {
      name = "which";
      packageName = "which";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.1.tgz";
        sha512 = "HxJdYWq1MTIQbJ3nw0cqssHoTNU267KlrDuGZ1WYlxDStUtKUhOaJmh112/TZmHxxUfuJqPXSOm7tDyas0OSIQ==";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
  };
in
{
  "grunt-^0.4.5" = nodeEnv.buildNodePackage {
    name = "grunt";
    packageName = "grunt";
    version = "0.4.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz";
      sha1 = "56937cd5194324adff6d207631832a9d6ba4e7f0";
    };
    dependencies = [
      sources."abbrev-1.1.1"
      (sources."argparse-0.1.16" // {
        dependencies = [
          sources."underscore.string-2.4.0"
        ];
      })
      sources."async-0.1.22"
      sources."coffee-script-1.3.3"
      sources."colors-0.6.2"
      sources."dateformat-1.0.2-1.2.3"
      sources."esprima-1.0.4"
      sources."eventemitter2-0.4.14"
      sources."exit-0.1.2"
      (sources."findup-sync-0.1.3" // {
        dependencies = [
          sources."glob-3.2.11"
          sources."lodash-2.4.2"
          sources."minimatch-0.3.0"
        ];
      })
      sources."getobject-0.1.0"
      (sources."glob-3.1.21" // {
        dependencies = [
          sources."inherits-1.0.2"
        ];
      })
      sources."graceful-fs-1.2.3"
      (sources."grunt-legacy-log-0.1.3" // {
        dependencies = [
          sources."lodash-2.4.2"
          sources."underscore.string-2.3.3"
        ];
      })
      (sources."grunt-legacy-log-utils-0.1.1" // {
        dependencies = [
          sources."lodash-2.4.2"
          sources."underscore.string-2.3.3"
        ];
      })
      sources."grunt-legacy-util-0.2.0"
      sources."hooker-0.2.3"
      sources."iconv-lite-0.2.11"
      sources."inherits-2.0.3"
      sources."js-yaml-2.0.5"
      sources."lodash-0.9.2"
      sources."lru-cache-2.7.3"
      sources."minimatch-0.2.14"
      sources."nopt-1.0.10"
      sources."rimraf-2.2.8"
      sources."sigmund-1.0.1"
      sources."underscore-1.7.0"
      sources."underscore.string-2.2.1"
      sources."which-1.0.9"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The JavaScript Task Runner";
      homepage = http://gruntjs.com/;
    };
    production = true;
    bypassCache = true;
  };
  "grunt-banner-^0.6.0" = nodeEnv.buildNodePackage {
    name = "grunt-banner";
    packageName = "grunt-banner";
    version = "0.6.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/grunt-banner/-/grunt-banner-0.6.0.tgz";
      sha1 = "3f879021d123fa58a7ba5a0b6fb6be412b5885ac";
    };
    dependencies = [
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."chalk-1.1.3"
      sources."escape-string-regexp-1.0.5"
      sources."has-ansi-2.0.0"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Adds a simple banner to files";
      homepage = https://github.com/mattstyles/grunt-banner;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "grunt-check-dependencies-^0.12.0" = nodeEnv.buildNodePackage {
    name = "grunt-check-dependencies";
    packageName = "grunt-check-dependencies";
    version = "0.12.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/grunt-check-dependencies/-/grunt-check-dependencies-0.12.0.tgz";
      sha1 = "797c08752a5917049f11817cefeeacdc220667da";
    };
    dependencies = [
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."arr-diff-2.0.0"
      sources."arr-flatten-1.1.0"
      sources."array-unique-0.2.1"
      sources."babel-runtime-6.26.0"
      sources."bower-config-1.4.1"
      sources."braces-1.8.5"
      sources."chalk-1.1.3"
      sources."check-dependencies-0.12.3"
      sources."core-js-2.6.5"
      sources."detect-file-0.1.0"
      sources."escape-string-regexp-1.0.5"
      sources."expand-brackets-0.1.5"
      sources."expand-range-1.8.2"
      sources."expand-tilde-1.2.2"
      sources."extglob-0.3.2"
      sources."filename-regex-2.0.1"
      sources."fill-range-2.2.4"
      sources."findup-sync-0.4.3"
      sources."for-in-1.0.2"
      sources."for-own-0.1.5"
      sources."fs-exists-sync-0.1.0"
      sources."glob-base-0.3.0"
      sources."glob-parent-2.0.0"
      sources."global-modules-0.2.3"
      sources."global-prefix-0.1.5"
      sources."graceful-fs-4.1.15"
      sources."has-ansi-2.0.0"
      sources."homedir-polyfill-1.0.1"
      sources."ini-1.3.5"
      sources."is-buffer-1.1.6"
      sources."is-dotfile-1.0.3"
      sources."is-equal-shallow-0.1.3"
      sources."is-extendable-0.1.1"
      sources."is-extglob-1.0.0"
      sources."is-glob-2.0.1"
      sources."is-number-2.1.0"
      sources."is-posix-bracket-0.1.1"
      sources."is-primitive-2.0.0"
      sources."is-windows-0.2.0"
      sources."isarray-1.0.0"
      sources."isexe-2.0.0"
      sources."isobject-2.1.0"
      sources."kind-of-3.2.2"
      sources."lodash-4.17.11"
      sources."lodash.clonedeep-4.5.0"
      sources."math-random-1.0.4"
      sources."micromatch-2.3.11"
      sources."minimist-1.2.0"
      sources."mout-1.1.0"
      sources."normalize-path-2.1.1"
      sources."object.omit-2.0.1"
      (sources."optimist-0.6.1" // {
        dependencies = [
          sources."minimist-0.0.10"
        ];
      })
      sources."os-homedir-1.0.2"
      sources."os-tmpdir-1.0.2"
      sources."osenv-0.1.5"
      sources."parse-glob-3.0.4"
      sources."parse-passwd-1.0.0"
      sources."preserve-0.2.0"
      (sources."randomatic-3.1.1" // {
        dependencies = [
          sources."is-number-4.0.0"
          sources."kind-of-6.0.2"
        ];
      })
      sources."regenerator-runtime-0.11.1"
      sources."regex-cache-0.4.4"
      sources."remove-trailing-separator-1.1.0"
      sources."repeat-element-1.1.3"
      sources."repeat-string-1.6.1"
      sources."resolve-dir-0.1.1"
      sources."semver-5.6.0"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
      sources."untildify-2.1.0"
      sources."which-1.3.1"
      sources."wordwrap-0.0.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Checks if currently installed npm dependencies are installed in the exact same versions that are specified in package.json.";
      homepage = https://github.com/mgol/grunt-check-dependencies;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "grunt-contrib-clean-^1.0.0" = nodeEnv.buildNodePackage {
    name = "grunt-contrib-clean";
    packageName = "grunt-contrib-clean";
    version = "1.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/grunt-contrib-clean/-/grunt-contrib-clean-1.1.0.tgz";
      sha1 = "564abf2d0378a983a15b9e3f30ee75b738c40638";
    };
    dependencies = [
      sources."async-1.5.2"
      sources."balanced-match-1.0.0"
      sources."brace-expansion-1.1.11"
      sources."concat-map-0.0.1"
      sources."fs.realpath-1.0.0"
      sources."glob-7.1.3"
      sources."inflight-1.0.6"
      sources."inherits-2.0.3"
      sources."minimatch-3.0.4"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."rimraf-2.6.3"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Clean files and folders";
      homepage = "https://github.com/gruntjs/grunt-contrib-clean#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "grunt-contrib-copy-^1.0.0" = nodeEnv.buildNodePackage {
    name = "grunt-contrib-copy";
    packageName = "grunt-contrib-copy";
    version = "1.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/grunt-contrib-copy/-/grunt-contrib-copy-1.0.0.tgz";
      sha1 = "7060c6581e904b8ab0d00f076e0a8f6e3e7c3573";
    };
    dependencies = [
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."chalk-1.1.3"
      sources."escape-string-regexp-1.0.5"
      sources."file-sync-cmp-0.1.1"
      sources."has-ansi-2.0.0"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Copy files and folders";
      homepage = "https://github.com/gruntjs/grunt-contrib-copy#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "grunt-stripcomments-^0.5.0" = nodeEnv.buildNodePackage {
    name = "grunt-stripcomments";
    packageName = "grunt-stripcomments";
    version = "0.5.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/grunt-stripcomments/-/grunt-stripcomments-0.5.0.tgz";
      sha1 = "74544c1301754ace80f42b17c993bb10312ec78b";
    };
    dependencies = [
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."chalk-1.1.3"
      sources."escape-string-regexp-1.0.5"
      sources."has-ansi-2.0.0"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Remove comments from code";
      homepage = https://github.com/kkemple/grunt-stripcomments;
    };
    production = true;
    bypassCache = true;
  };
  "grunt-mkdir-^1.0.0" = nodeEnv.buildNodePackage {
    name = "grunt-mkdir";
    packageName = "grunt-mkdir";
    version = "1.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/grunt-mkdir/-/grunt-mkdir-1.0.0.tgz";
      sha1 = "73e1a26ac24a08596363f4dd954b0d32485e58e9";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Create directories with Grunt.";
      homepage = https://github.com/rubenv/grunt-mkdir;
    };
    production = true;
    bypassCache = true;
  };
}