# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "abbrev-1.1.1" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
        sha512 = "nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q==";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "applause-1.2.2" = {
      name = "applause";
      packageName = "applause";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/applause/-/applause-1.2.2.tgz";
        sha1 = "a8468579e81f67397bb5634c29953bedcd0f56c0";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "array-find-index-1.0.2" = {
      name = "array-find-index";
      packageName = "array-find-index";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-find-index/-/array-find-index-1.0.2.tgz";
        sha1 = "df010aa1287e164bbda6f9723b0a96a1ec4187a1";
      };
    };
    "async-1.5.2" = {
      name = "async";
      packageName = "async";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.5.2.tgz";
        sha1 = "ec6a61ae56480c0c3cb241c95618e20892f9672a";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "camelcase-2.1.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-2.1.1.tgz";
        sha1 = "7c1d16d679a1bbe59ca02cacecfb011e201f5a1f";
      };
    };
    "camelcase-keys-2.1.0" = {
      name = "camelcase-keys";
      packageName = "camelcase-keys";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase-keys/-/camelcase-keys-2.1.0.tgz";
        sha1 = "308beeaffdf28119051efa1d932213c91b8f92e7";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "clone-2.1.2" = {
      name = "clone";
      packageName = "clone";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-2.1.2.tgz";
        sha1 = "1b7f4b9f591f1e8f83670401600345a02887435f";
      };
    };
    "clone-buffer-1.0.0" = {
      name = "clone-buffer";
      packageName = "clone-buffer";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone-buffer/-/clone-buffer-1.0.0.tgz";
        sha1 = "e3e25b207ac4e701af721e2cb5a16792cac3dc58";
      };
    };
    "clone-stats-1.0.0" = {
      name = "clone-stats";
      packageName = "clone-stats";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone-stats/-/clone-stats-1.0.0.tgz";
        sha1 = "b3782dff8bb5474e18b9b6bf0fdfe782f8777680";
      };
    };
    "cloneable-readable-1.1.2" = {
      name = "cloneable-readable";
      packageName = "cloneable-readable";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cloneable-readable/-/cloneable-readable-1.1.2.tgz";
        sha512 = "Bq6+4t+lbM8vhTs/Bef5c5AdEMtapp/iFb6+s4/Hh9MVTt8OLKH7ZOOZSCT+Ys7hsHvqv0GuMPJ1lnQJVHvxpg==";
      };
    };
    "coffee-script-1.10.0" = {
      name = "coffee-script";
      packageName = "coffee-script";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/coffee-script/-/coffee-script-1.10.0.tgz";
        sha1 = "12938bcf9be1948fa006f92e0c4c9e81705108c0";
      };
    };
    "coffee-script-1.12.7" = {
      name = "coffee-script";
      packageName = "coffee-script";
      version = "1.12.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/coffee-script/-/coffee-script-1.12.7.tgz";
        sha512 = "fLeEhqwymYat/MpTPUjSKHVYYl0ec2mOyALEMLmzr5i1isuG+6jfI2j2d5oBO3VIzgUXgBVIcOT9uH1TFxBckw==";
      };
    };
    "colors-1.1.2" = {
      name = "colors";
      packageName = "colors";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.1.2.tgz";
        sha1 = "168a4701756b6a7f51a12ce0c97bfa28c084ed63";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "cson-parser-1.3.5" = {
      name = "cson-parser";
      packageName = "cson-parser";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cson-parser/-/cson-parser-1.3.5.tgz";
        sha1 = "7ec675e039145533bf2a6a856073f1599d9c2d24";
      };
    };
    "currently-unhandled-0.4.1" = {
      name = "currently-unhandled";
      packageName = "currently-unhandled";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/currently-unhandled/-/currently-unhandled-0.4.1.tgz";
        sha1 = "988df33feab191ef799a61369dd76c17adf957ea";
      };
    };
    "dateformat-1.0.12" = {
      name = "dateformat";
      packageName = "dateformat";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/dateformat/-/dateformat-1.0.12.tgz";
        sha1 = "9f124b67594c937ff706932e4a642cca8dbbfee9";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha1 = "f6534d15148269b20352e7bee26f501f9a191290";
      };
    };
    "error-ex-1.3.2" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.2.tgz";
        sha512 = "7dFHNmqeFSEt2ZBsCriorKnn3Z2pj+fd9kmI6QoWw4//DL+icEBfc0U7qJCisqrTsKTjw4fNFy2pW9OqStD84g==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esprima-2.7.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-2.7.3.tgz";
        sha1 = "96e3b70d5779f6ad49cd032673d1c312767ba581";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "eventemitter2-0.4.14" = {
      name = "eventemitter2";
      packageName = "eventemitter2";
      version = "0.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter2/-/eventemitter2-0.4.14.tgz";
        sha1 = "8f61b75cde012b2e9eb284d4545583b5643b61ab";
      };
    };
    "exit-0.1.2" = {
      name = "exit";
      packageName = "exit";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/exit/-/exit-0.1.2.tgz";
        sha1 = "0632638f8d877cc82107d30a0fff1a17cba1cd0c";
      };
    };
    "file-sync-cmp-0.1.1" = {
      name = "file-sync-cmp";
      packageName = "file-sync-cmp";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-sync-cmp/-/file-sync-cmp-0.1.1.tgz";
        sha1 = "a5e7a8ffbfa493b43b923bbd4ca89a53b63b612b";
      };
    };
    "find-up-1.1.2" = {
      name = "find-up";
      packageName = "find-up";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-1.1.2.tgz";
        sha1 = "6b2e9822b1a2ce0a60ab64d610eccad53cb24d0f";
      };
    };
    "findup-sync-0.3.0" = {
      name = "findup-sync";
      packageName = "findup-sync";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/findup-sync/-/findup-sync-0.3.0.tgz";
        sha1 = "37930aa5d816b777c03445e1966cc6790a4c0b16";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "get-stdin-4.0.1" = {
      name = "get-stdin";
      packageName = "get-stdin";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stdin/-/get-stdin-4.0.1.tgz";
        sha1 = "b968c6b0a04384324902e8bf1a5df32579a450fe";
      };
    };
    "getobject-0.1.0" = {
      name = "getobject";
      packageName = "getobject";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/getobject/-/getobject-0.1.0.tgz";
        sha1 = "047a449789fa160d018f5486ed91320b6ec7885c";
      };
    };
    "glob-5.0.15" = {
      name = "glob";
      packageName = "glob";
      version = "5.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-5.0.15.tgz";
        sha1 = "1bc936b9e02f4a603fcc222ecf7633d30b8b93b1";
      };
    };
    "glob-7.0.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.0.6.tgz";
        sha1 = "211bafaf49e525b8cd93260d14ab136152b3f57a";
      };
    };
    "glob-7.1.3" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.3.tgz";
        sha512 = "vcfuiIxogLV4DlGBHIUOwI0IbrJ8HWPc4MU7HzviGeNho/UJDfi6B5p3sHeWIQ0KGIU0Jpxi5ZHxemQfLkkAwQ==";
      };
    };
    "graceful-fs-4.1.15" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.15.tgz";
        sha512 = "6uHUhOPEBgQ24HM+r6b/QwWfZq+yiFcipKFrOFiBEnWdy5sdzYoi+pJeQaPI5qOLRFqWmAXUPQNsielzdLoecA==";
      };
    };
    "grunt-cli-1.2.0" = {
      name = "grunt-cli";
      packageName = "grunt-cli";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz";
        sha1 = "562b119ebb069ddb464ace2845501be97b35b6a8";
      };
    };
    "grunt-known-options-1.1.1" = {
      name = "grunt-known-options";
      packageName = "grunt-known-options";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-known-options/-/grunt-known-options-1.1.1.tgz";
        sha512 = "cHwsLqoighpu7TuYj5RonnEuxGVFnztcUqTqp5rXFGYL4OuPFofwC4Ycg7n9fYwvK6F5WbYgeVOwph9Crs2fsQ==";
      };
    };
    "grunt-legacy-log-1.0.2" = {
      name = "grunt-legacy-log";
      packageName = "grunt-legacy-log";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-log/-/grunt-legacy-log-1.0.2.tgz";
        sha512 = "WdedTJ/6zCXnI/coaouzqvkI19uwqbcPkdsXiDRKJyB5rOUlOxnCnTVbpeUdEckKVir2uHF3rDBYppj2p6N3+g==";
      };
    };
    "grunt-legacy-log-utils-1.0.0" = {
      name = "grunt-legacy-log-utils";
      packageName = "grunt-legacy-log-utils";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-log-utils/-/grunt-legacy-log-utils-1.0.0.tgz";
        sha1 = "a7b8e2d0fb35b5a50f4af986fc112749ebc96f3d";
      };
    };
    "grunt-legacy-util-1.0.0" = {
      name = "grunt-legacy-util";
      packageName = "grunt-legacy-util";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-util/-/grunt-legacy-util-1.0.0.tgz";
        sha1 = "386aa78dc6ed50986c2b18957265b1b48abb9b86";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "hooker-0.2.3" = {
      name = "hooker";
      packageName = "hooker";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hooker/-/hooker-0.2.3.tgz";
        sha1 = "b834f723cc4a242aa65963459df6d984c5d3d959";
      };
    };
    "hosted-git-info-2.7.1" = {
      name = "hosted-git-info";
      packageName = "hosted-git-info";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.7.1.tgz";
        sha512 = "7T/BxH19zbcCTa8XkMlbK5lTo1WtgkFi3GvdWEyNuc4Vex7/9Dqbnpsf4JMydcfj9HCg4zUWFTL3Za6lapg5/w==";
      };
    };
    "iconv-lite-0.4.24" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz";
        sha512 = "v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==";
      };
    };
    "indent-string-2.1.0" = {
      name = "indent-string";
      packageName = "indent-string";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/indent-string/-/indent-string-2.1.0.tgz";
        sha1 = "8e2d48348742121b4a8218b7a137e9a52049dc80";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "is-finite-1.0.2" = {
      name = "is-finite";
      packageName = "is-finite";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-finite/-/is-finite-1.0.2.tgz";
        sha1 = "cc6677695602be550ef11e8b4aa6305342b6d0aa";
      };
    };
    "is-utf8-0.2.1" = {
      name = "is-utf8";
      packageName = "is-utf8";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-utf8/-/is-utf8-0.2.1.tgz";
        sha1 = "4b0da1442104d1b336340e80797e865cf39f7d72";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "js-yaml-3.12.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.12.1.tgz";
        sha512 = "um46hB9wNOKlwkHgiuyEVAybXBjwFUV0Z/RaHJblRd9DXltue9FTYvzCr9ErQrK9Adz5MU4gHWVaNUfdmrC8qA==";
      };
    };
    "js-yaml-3.5.5" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.5.5.tgz";
        sha1 = "0377c38017cabc7322b0d1fbcd25a491641f2fbe";
      };
    };
    "load-json-file-1.1.0" = {
      name = "load-json-file";
      packageName = "load-json-file";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-json-file/-/load-json-file-1.1.0.tgz";
        sha1 = "956905708d58b4bab4c2261b04f59f31c99374c0";
      };
    };
    "lodash-3.10.1" = {
      name = "lodash";
      packageName = "lodash";
      version = "3.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-3.10.1.tgz";
        sha1 = "5bf45e8e49ba4189e17d482789dfd15bd140b7b6";
      };
    };
    "lodash-4.17.11" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.11.tgz";
        sha512 = "cQKh8igo5QUhZ7lg38DYWAxMvjSAKG0A8wGSVimP07SIUEK2UO+arSRKbRZWtelMtN5V0Hkwh5ryOto/SshYIg==";
      };
    };
    "lodash-4.3.0" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.3.0.tgz";
        sha1 = "efd9c4a6ec53f3b05412429915c3e4824e4d25a4";
      };
    };
    "loud-rejection-1.6.0" = {
      name = "loud-rejection";
      packageName = "loud-rejection";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loud-rejection/-/loud-rejection-1.6.0.tgz";
        sha1 = "5b46f80147edee578870f086d04821cf998e551f";
      };
    };
    "map-obj-1.0.1" = {
      name = "map-obj";
      packageName = "map-obj";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-obj/-/map-obj-1.0.1.tgz";
        sha1 = "d933ceb9205d82bdcf4886f6742bdc2b4dea146d";
      };
    };
    "meow-3.7.0" = {
      name = "meow";
      packageName = "meow";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/meow/-/meow-3.7.0.tgz";
        sha1 = "72cb668b425228290abbfa856892587308a801fb";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "normalize-package-data-2.5.0" = {
      name = "normalize-package-data";
      packageName = "normalize-package-data";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-2.5.0.tgz";
        sha512 = "/5CMN3T0R4XTj4DcGaexo+roZSdSFW/0AOOTROrjxzCG1wrWXEsGbRKevjlIL+ZDE4sZlJr5ED4YW0yqmkK+eA==";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "parse-json-2.2.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-2.2.0.tgz";
        sha1 = "f480f40434ef80741f8469099f8dea18f55a4dc9";
      };
    };
    "path-exists-2.1.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-2.1.0.tgz";
        sha1 = "0feb6c64f0fc518d9a754dd5efb62c7022761f4b";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-parse-1.0.6" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.6.tgz";
        sha512 = "GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==";
      };
    };
    "path-type-1.1.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-1.1.0.tgz";
        sha1 = "59c44f7ee491da704da415da5a4070ba4f8fe441";
      };
    };
    "pify-2.3.0" = {
      name = "pify";
      packageName = "pify";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-2.3.0.tgz";
        sha1 = "ed141a6ac043a849ea588498e7dca8b15330e90c";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "process-nextick-args-2.0.0" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.0.tgz";
        sha512 = "MtEC1TqN0EU5nephaJ4rAtThHtC86dNN9qCuEhtshvpVBkAW5ZO7BASN9REnF9eoXGcRub+pFuKEpOHE+HbEMw==";
      };
    };
    "read-pkg-1.1.0" = {
      name = "read-pkg";
      packageName = "read-pkg";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg/-/read-pkg-1.1.0.tgz";
        sha1 = "f5ffaa5ecd29cb31c0474bca7d756b6bb29e3f28";
      };
    };
    "read-pkg-up-1.0.1" = {
      name = "read-pkg-up";
      packageName = "read-pkg-up";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg-up/-/read-pkg-up-1.0.1.tgz";
        sha1 = "9d63c13276c065918d57f002a57f40a1b643fb02";
      };
    };
    "readable-stream-2.3.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.6.tgz";
        sha512 = "tQtKA9WIAhBF3+VLAseyMqZeBjW0AHJoxOtYqSUZNJxauErmLbVm2FW1y+J/YA9dUrAC39ITejlZWhVIwawkKw==";
      };
    };
    "redent-1.0.0" = {
      name = "redent";
      packageName = "redent";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redent/-/redent-1.0.0.tgz";
        sha1 = "cf916ab1fd5f1f16dfb20822dd6ec7f730c2afde";
      };
    };
    "remove-trailing-separator-1.1.0" = {
      name = "remove-trailing-separator";
      packageName = "remove-trailing-separator";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remove-trailing-separator/-/remove-trailing-separator-1.1.0.tgz";
        sha1 = "c24bce2a283adad5bc3f58e0d48249b92379d8ef";
      };
    };
    "repeating-2.0.1" = {
      name = "repeating";
      packageName = "repeating";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeating/-/repeating-2.0.1.tgz";
        sha1 = "5214c53a926d3552707527fbab415dbc08d06dda";
      };
    };
    "replace-ext-1.0.0" = {
      name = "replace-ext";
      packageName = "replace-ext";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/replace-ext/-/replace-ext-1.0.0.tgz";
        sha1 = "de63128373fcbf7c3ccfa4de5a480c45a67958eb";
      };
    };
    "resolve-1.1.7" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.1.7.tgz";
        sha1 = "203114d82ad2c5ed9e8e0411b3932875e889e97b";
      };
    };
    "resolve-1.10.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.10.0.tgz";
        sha512 = "3sUr9aq5OfSg2S9pNtPA9hL1FVEAjvfOC4leW0SNf/mpnaakz2a9femSd6LqAww2RaFctwyf1lCqnTHuF1rxDg==";
      };
    };
    "rimraf-2.2.8" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz";
        sha1 = "e439be2aaee327321952730f99a8929e4fc50582";
      };
    };
    "rimraf-2.6.3" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.6.3.tgz";
        sha512 = "mwqeW5XsA2qAejG46gYdENaxXjx9onRNCfn7L0duuP4hCuTIi/QO7PDK07KJfp1d+izWPrzEJDcSqBa0OZQriA==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "semver-5.6.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.6.0.tgz";
        sha512 = "RS9R6R35NYgQn++fkDWaOmqGoj4Ek9gGs+DPxNUZKuwE183xjJroKvyo1IzVFeXvUrvmALy6FWD5xrdJT25gMg==";
      };
    };
    "signal-exit-3.0.2" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.2.tgz";
        sha1 = "b5fdc08f1287ea1178628e415e25132b73646c6d";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "spdx-correct-3.1.0" = {
      name = "spdx-correct";
      packageName = "spdx-correct";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-correct/-/spdx-correct-3.1.0.tgz";
        sha512 = "lr2EZCctC2BNR7j7WzJ2FpDznxky1sjfxvvYEyzxNyb6lZXHODmEoJeFu4JupYlkfha1KZpJyoqiJ7pgA1qq8Q==";
      };
    };
    "spdx-exceptions-2.2.0" = {
      name = "spdx-exceptions";
      packageName = "spdx-exceptions";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-exceptions/-/spdx-exceptions-2.2.0.tgz";
        sha512 = "2XQACfElKi9SlVb1CYadKDXvoajPgBVPn/gOQLrTvHdElaVhr7ZEbqJaRnJLVNeaI4cMEAgVCeBMKF6MWRDCRA==";
      };
    };
    "spdx-expression-parse-3.0.0" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-3.0.0.tgz";
        sha512 = "Yg6D3XpRD4kkOmTpdgbUiEJFKghJH03fiC1OPll5h/0sO6neh2jqRDVHOQ4o/LMea0tgCkbMgea5ip/e+MkWyg==";
      };
    };
    "spdx-license-ids-3.0.3" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-3.0.3.tgz";
        sha512 = "uBIcIl3Ih6Phe3XHK1NqboJLdGfwr1UN3k6wSD1dZpmPsIkb8AGNbZYJ1fOBk834+Gxy8rpfDxrS6XLEMZMY2g==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "strip-bom-2.0.0" = {
      name = "strip-bom";
      packageName = "strip-bom";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-bom/-/strip-bom-2.0.0.tgz";
        sha1 = "6219a85616520491f35788bdbf1447a99c7e6b0e";
      };
    };
    "strip-indent-1.0.1" = {
      name = "strip-indent";
      packageName = "strip-indent";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-indent/-/strip-indent-1.0.1.tgz";
        sha1 = "0c7962a6adefa7bbd4ac366460a638552ae1a0a2";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "trim-newlines-1.0.0" = {
      name = "trim-newlines";
      packageName = "trim-newlines";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/trim-newlines/-/trim-newlines-1.0.0.tgz";
        sha1 = "5887966bb582a4503a41eb524f7d35011815a613";
      };
    };
    "underscore.string-3.2.3" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "3.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-3.2.3.tgz";
        sha1 = "806992633665d5e5fcb4db1fb3a862eb68e9e6da";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "validate-npm-package-license-3.0.4" = {
      name = "validate-npm-package-license";
      packageName = "validate-npm-package-license";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-license/-/validate-npm-package-license-3.0.4.tgz";
        sha512 = "DpKm2Ui/xN7/HQKCtpZxoRWBhZ9Z0kqtygG8XCgNQ8ZlDnxuQmWhj566j8fN4Cu3/JmbhsDo7fcAJq4s9h27Ew==";
      };
    };
    "vinyl-2.2.0" = {
      name = "vinyl";
      packageName = "vinyl";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vinyl/-/vinyl-2.2.0.tgz";
        sha512 = "MBH+yP0kC/GQ5GwBqrTPTzEfiiLjta7hTtvQtbxBgTeSXsmKQRQecjibMbxIXzVT3Y9KJK+drOz1/k+vsu8Nkg==";
      };
    };
    "vinyl-sourcemaps-apply-0.2.1" = {
      name = "vinyl-sourcemaps-apply";
      packageName = "vinyl-sourcemaps-apply";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vinyl-sourcemaps-apply/-/vinyl-sourcemaps-apply-0.2.1.tgz";
        sha1 = "ab6549d61d172c2b1b87be5c508d239c8ef87705";
      };
    };
    "which-1.2.14" = {
      name = "which";
      packageName = "which";
      version = "1.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.2.14.tgz";
        sha1 = "9a87c4378f03e827cecaf1acdf56c736c01c14e5";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
  };
in
{
  "google-closure-compiler-20170626.0.0" = nodeEnv.buildNodePackage {
    name = "google-closure-compiler";
    packageName = "google-closure-compiler";
    version = "20170626.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/google-closure-compiler/-/google-closure-compiler-20170626.0.0.tgz";
      sha1 = "0d2a975d345e1aa13b37e55832509d59ba8a87e0";
    };
    dependencies = [
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."chalk-1.1.3"
      sources."clone-2.1.2"
      sources."clone-buffer-1.0.0"
      sources."clone-stats-1.0.0"
      sources."cloneable-readable-1.1.2"
      sources."core-util-is-1.0.2"
      sources."escape-string-regexp-1.0.5"
      sources."has-ansi-2.0.0"
      sources."inherits-2.0.3"
      sources."isarray-1.0.0"
      sources."process-nextick-args-2.0.0"
      sources."readable-stream-2.3.6"
      sources."remove-trailing-separator-1.1.0"
      sources."replace-ext-1.0.0"
      sources."safe-buffer-5.1.2"
      sources."source-map-0.5.7"
      sources."string_decoder-1.1.1"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
      sources."util-deprecate-1.0.2"
      sources."vinyl-2.2.0"
      sources."vinyl-sourcemaps-apply-0.2.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Check, compile, optimize and compress Javascript with Closure-Compiler";
      homepage = https://developers.google.com/closure/compiler/;
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
  };
  "grunt-1.0.1" = nodeEnv.buildNodePackage {
    name = "grunt";
    packageName = "grunt";
    version = "1.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/grunt/-/grunt-1.0.1.tgz";
      sha1 = "e8778764e944b18f32bb0f10b9078475c9dfb56b";
    };
    dependencies = [
      sources."abbrev-1.1.1"
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."argparse-1.0.10"
      sources."array-find-index-1.0.2"
      sources."async-1.5.2"
      sources."balanced-match-1.0.0"
      sources."brace-expansion-1.1.11"
      sources."camelcase-2.1.1"
      sources."camelcase-keys-2.1.0"
      sources."chalk-1.1.3"
      sources."coffee-script-1.10.0"
      sources."colors-1.1.2"
      sources."concat-map-0.0.1"
      sources."currently-unhandled-0.4.1"
      sources."dateformat-1.0.12"
      sources."decamelize-1.2.0"
      sources."error-ex-1.3.2"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-2.7.3"
      sources."eventemitter2-0.4.14"
      sources."exit-0.1.2"
      sources."find-up-1.1.2"
      (sources."findup-sync-0.3.0" // {
        dependencies = [
          sources."glob-5.0.15"
        ];
      })
      sources."fs.realpath-1.0.0"
      sources."get-stdin-4.0.1"
      sources."getobject-0.1.0"
      sources."glob-7.0.6"
      sources."graceful-fs-4.1.15"
      (sources."grunt-cli-1.2.0" // {
        dependencies = [
          sources."resolve-1.1.7"
        ];
      })
      sources."grunt-known-options-1.1.1"
      sources."grunt-legacy-log-1.0.2"
      (sources."grunt-legacy-log-utils-1.0.0" // {
        dependencies = [
          sources."lodash-4.3.0"
        ];
      })
      (sources."grunt-legacy-util-1.0.0" // {
        dependencies = [
          sources."lodash-4.3.0"
        ];
      })
      sources."has-ansi-2.0.0"
      sources."hooker-0.2.3"
      sources."hosted-git-info-2.7.1"
      sources."iconv-lite-0.4.24"
      sources."indent-string-2.1.0"
      sources."inflight-1.0.6"
      sources."inherits-2.0.3"
      sources."is-arrayish-0.2.1"
      sources."is-finite-1.0.2"
      sources."is-utf8-0.2.1"
      sources."isexe-2.0.0"
      sources."js-yaml-3.5.5"
      sources."load-json-file-1.1.0"
      sources."lodash-4.17.11"
      sources."loud-rejection-1.6.0"
      sources."map-obj-1.0.1"
      sources."meow-3.7.0"
      sources."minimatch-3.0.4"
      sources."minimist-1.2.0"
      sources."nopt-3.0.6"
      sources."normalize-package-data-2.5.0"
      sources."number-is-nan-1.0.1"
      sources."object-assign-4.1.1"
      sources."once-1.4.0"
      sources."parse-json-2.2.0"
      sources."path-exists-2.1.0"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.6"
      sources."path-type-1.1.0"
      sources."pify-2.3.0"
      sources."pinkie-2.0.4"
      sources."pinkie-promise-2.0.1"
      sources."read-pkg-1.1.0"
      sources."read-pkg-up-1.0.1"
      sources."redent-1.0.0"
      sources."repeating-2.0.1"
      sources."resolve-1.10.0"
      sources."rimraf-2.2.8"
      sources."safer-buffer-2.1.2"
      sources."semver-5.6.0"
      sources."signal-exit-3.0.2"
      sources."spdx-correct-3.1.0"
      sources."spdx-exceptions-2.2.0"
      sources."spdx-expression-parse-3.0.0"
      sources."spdx-license-ids-3.0.3"
      sources."sprintf-js-1.0.3"
      sources."strip-ansi-3.0.1"
      sources."strip-bom-2.0.0"
      sources."strip-indent-1.0.1"
      sources."supports-color-2.0.0"
      sources."trim-newlines-1.0.0"
      sources."underscore.string-3.2.3"
      sources."validate-npm-package-license-3.0.4"
      sources."which-1.2.14"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The JavaScript Task Runner";
      homepage = http://gruntjs.com/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "grunt-contrib-clean-1.0.0" = nodeEnv.buildNodePackage {
    name = "grunt-contrib-clean";
    packageName = "grunt-contrib-clean";
    version = "1.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/grunt-contrib-clean/-/grunt-contrib-clean-1.0.0.tgz";
      sha1 = "6b2ed94117e2c7ffe32ee04578c96fe4625a9b6d";
    };
    dependencies = [
      sources."async-1.5.2"
      sources."balanced-match-1.0.0"
      sources."brace-expansion-1.1.11"
      sources."concat-map-0.0.1"
      sources."fs.realpath-1.0.0"
      sources."glob-7.1.3"
      sources."inflight-1.0.6"
      sources."inherits-2.0.3"
      sources."minimatch-3.0.4"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."rimraf-2.6.3"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Clean files and folders";
      homepage = https://github.com/gruntjs/grunt-contrib-clean;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "grunt-contrib-concat-1.0.1" = nodeEnv.buildNodePackage {
    name = "grunt-contrib-concat";
    packageName = "grunt-contrib-concat";
    version = "1.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/grunt-contrib-concat/-/grunt-contrib-concat-1.0.1.tgz";
      sha1 = "61509863084e871d7e86de48c015259ed97745bd";
    };
    dependencies = [
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."chalk-1.1.3"
      sources."escape-string-regexp-1.0.5"
      sources."has-ansi-2.0.0"
      sources."source-map-0.5.7"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Concatenate files.";
      homepage = "https://github.com/gruntjs/grunt-contrib-concat#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "grunt-replace-1.0.1" = nodeEnv.buildNodePackage {
    name = "grunt-replace";
    packageName = "grunt-replace";
    version = "1.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/grunt-replace/-/grunt-replace-1.0.1.tgz";
      sha1 = "90a79532fb89041fe427c87d425238b0f886651a";
    };
    dependencies = [
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      (sources."applause-1.2.2" // {
        dependencies = [
          sources."lodash-3.10.1"
        ];
      })
      sources."argparse-1.0.10"
      sources."chalk-1.1.3"
      sources."coffee-script-1.12.7"
      sources."cson-parser-1.3.5"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-4.0.1"
      sources."file-sync-cmp-0.1.1"
      sources."has-ansi-2.0.0"
      sources."js-yaml-3.12.1"
      sources."lodash-4.17.11"
      sources."sprintf-js-1.0.3"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Replace text patterns with applause.";
      homepage = "https://github.com/outatime/grunt-replace#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  "grunt-split-file-1.0.1" = nodeEnv.buildNodePackage {
    name = "grunt-split-file";
    packageName = "grunt-split-file";
    version = "1.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/grunt-split-file/-/grunt-split-file-1.0.1.tgz";
      sha1 = "d581e8a753b69d4eddcdb1586f4793e60499b58e";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Split specified files into multiple parts.";
      homepage = https://github.com/kurohara/grunt-split-file;
    };
    production = true;
    bypassCache = true;
  };
}